### PR TITLE
Navigation can be achieved on up(left)/down(right) keyboard keys

### PR DESCRIPTION
**Pull request by sarveshwar-gavhane**

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Thanks @sarveshwar-gavhane.  I've noticed you're binding the key events on inview and was wondering what is the effect if the user is using the down arrow key to scroll down the course page, when they reach the blockslider?

**Comment by sarveshwar-gavhane** [comment]
@brian-learningpool  your absolutely right. i have considered that it may have more than one article in page so when the particular article comes inView it trigger if it goes out of it should unbind the event .... is there any better way to do that ?? or should bind the event from outside the inView ? so what can be done here..

**Comment by brian-learningpool** [comment]
@sarveshwar-gavhane, I was thinking more in terms of imagining the user experience.  

Not I haven't had time to test this yet, but if the user is scrolling down the page using the down arrow key, will the behaviour suddenly change to moving the blockslider right rather than continuing the scroll down the page?

**Comment by sarveshwar-gavhane** [comment]
@brian-learningpool  yeah this is the serious issue,if user scroll down the page using down arrow key, i have one solution for this, if user on the last block of the article in blockSlider, if he pressed Escape key, we can unbind the events so he can scroll down the page using down arrow key and again when that article having blockSlider will come inView we can bind the key event again so that blockSlider functionality will still there and also user can scroll down the page using the down arrow key.... but will this be the feasible solution don't know ?

**Pull request closed without merging**
